### ISSUE TITLE
Reset back to original rotation and size

### ISSUE THREAD

**Issue by Abderezai** [kishikawakatsumi/PEPhotoCropEditor#16]
Hi,
I was wondering if you plan on adding a feature that would reset the crop area, image rotation, and view back to the first load state.
Thanks!

**Comment by rivera-ernesto** [comment]
I think that if you set again the crop view's image it will get reset to the original state.

``` obj-c
cropView.image = originalImage;
```

**Comment by Abderezai** [comment]
I just got around to testing that and it worked.
Thank you!

**Comment by kishikawakatsumi** [comment]
@rivera-ernesto Thank your for following.

**Comment by kishikawakatsumi** [comment]
Added `resetCropRect` method.
