### ISSUE TITLE
Disabled Rotation?

### ISSUE THREAD

**Issue by jasanchezsa** [kishikawakatsumi/PEPhotoCropEditor#48]
Firstly congratulations on the project. Sorry for my English.

You can disable the rotation?

Thank you very much.

**Comment by jasanchezsa** [comment]
Sorry

Just comment these lines of code:

```
UIRotationGestureRecognizer *rotationGestureRecognizer = [[UIRotationGestureRecognizer alloc] initWithTarget:self action:@selector(handleRotation:)];
rotationGestureRecognizer.delegate = self;
[self.scrollView addGestureRecognizer:rotationGestureRecognizer];
```

**Comment by DenVog** [comment]
I thought setting `[controller setRotationEnabled:NO];` in the openEditor method would address this, but it doesn't...
