### ISSUE TITLE
Will this app along with its framework be approved by the apple app store?

### ISSUE THREAD

**Issue by fresh83** [kishikawakatsumi/PEPhotoCropEditor#50]
question in title....i really dont want to submit a binary using this lib and end up waiting 7 days just to be rejected if i can find out in advance it will be rejected

**Comment by kishikawakatsumi** [comment]
Some apps using this library are available on App Store.
For example:

Ubiregi
https://itunes.apple.com/jp/app/yubireji2/id442910152?mt=8
↑ It is POS system app in iPad, I maintained.

Hogogh!
https://itunes.apple.com/jp/app/hogohho!-zi-gongno-huiya-gong/id793702635?mt=8
↑ It is photo album app for children. (Maybe Japanese store only.)

**Comment by brockboland** [comment]
Seems to be! I'm using it in http://shoot.sh/
